### ISSUE TITLE
gnome-shell-extension-tool is deprecated and does not enable extensions anymore

### ISSUE THREAD

**Issue by snyssen** [PeterMosmans/ansible-role-customize-gnome#22]
I noticed that none of the installed extensions were enabled under a Fedora 36 machine with GNOME 42.4.

Investigating further, it seems that the `gnome-shell-extension-tool -e <extension name>` command you use was deprecated in favor of `gnome-extensions enable <extension name>`. Executing the former no longer has any effect on the system, while the latter does.

Unfortunately the new command does not return any useful information (no text nor useful status code) upon completion, so there is no way to know if the command resulted in a change or not, but I guess it's better than the command not working at all...

I can open a pull request if you would like, but I am unsure how to handle what will probably be a breaking change for users on older GNOME versions, so I would like your opinion first.

**Comment by PeterMosmans** [comment]
Hey @snyssen , thanks for the heads-up: I was unaware of the deprecation.

I ❤️ pull requests: The most gentle way is probably to first use the deprecated command `gnome-shell-extension-tool`, and to allow that to fail. IF that fails, then `gnome-extensions` can be used.
That way, the PR will be backwards-compatible.

**Comment by snyssen** [comment]
Okay I'll see if I can provide a PR soon 😄 

(Great work on the role btw, I'm setting up automation for a new workstation and it has been a great help ❤️ )
