### ISSUE TITLE
Ansible Galaxy stuck at 0.2.8

### ISSUE THREAD

**Issue by snyssen** [PeterMosmans/ansible-role-customize-gnome#26]
Hi,

It seems the role at [Ansible Galaxy](https://galaxy.ansible.com/PeterMosmans/customize-gnome) is still stuck at version 0.2.8 even though you added tags for versions 0.2.9 and 0.2.10 on git. Maybe it is normal, but I am guessing it is not and maybe some push to Ansible Galaxy failed during CI?

**Comment by PeterMosmans** [comment]
Thanks for the heads-up @snyssen - that should have been performed automatically, the import. I'll do it manually, and close this issue when verified that it actually worked, the import

**Comment by PeterMosmans** [comment]
Hi @snyssen - version 0.2.10 is available through Galaxy. Thanks for your patience and the heads-up!

**Comment by snyssen** [comment]
Perfect, thank you! 🚀
