### ISSUE TITLE
Updating the ansible-galaxy repo

### ISSUE THREAD

**Issue by Xehnoh** [PeterMosmans/ansible-role-customize-gnome#36]
Hello I'm using your repo on ansible-galaxy via ansible Semaphore (which downloads from ansible-galaxy by default) and it doesn't implement the change you did to the tmp folders. I really like your stuff and I'd love if you would update it to the current version of this repo if that is possible.
Big thanks for making this!

**Comment by Xehnoh** [comment]
Thanks for the fast answer! If that works out that would be honestly great since my current workaround is using command line to run an extra task with this role on a specified set of hosts.

**Comment by PeterMosmans** [comment]
Thanks for your patience @Xehnoh - the role has now been imported, see https://galaxy.ansible.com/ui/standalone/roles/PeterMosmans/customize-gnome/versions/

Somehow there seems to be an issue with the namespace: Even though it's lowercase, the "legacy system" expected a case-sensitive name during importing.

**Comment by Xehnoh** [comment]
Thanks so much! Everything seems to look good, but regardless I will test it in the coming hours and if everything works I'll close this issue.  Again thank you so much.
